class Constants:
    EMPTY = 0
    BREADCRUMB = 1
    OBSTACLE = 2
    START = 3
    AGENT = 9
    EMPTY_X = "."
    BREADCRUMB_X = "b"
    OBSTACLE_X = "X"
    START_X = "S"
    AGENT_X = "A"
    EMPTY_REWARD = -1
    BREADCRUMB_REWARD = 10
    OBSTACLE_REWARD = -100
    UP = 0
    DOWN = 1
    LEFT = 2
    RIGHT = 3
    OBSTACLE_COORDS = [(1, 1), (1, 4), (2, 2), (3,4), (4, 2), (4, 4), (5, 4)]